## Red Neuronal coche con Keras y Tensorflow

#### Librerias

In [5]:
import numpy as np
from keras.models import Sequential
from keras.layers.core import Dense

#### Se cargan las entradas

In [6]:
datos_entrenamiento = np.array([[-1,0],[-1,1],[-1,-1],[0,-1],[0,1],[0,0],[1,1],[1,-1],[1,0]], "float32")

datos_entrenamiento

array([[-1.,  0.],
       [-1.,  1.],
       [-1., -1.],
       [ 0., -1.],
       [ 0.,  1.],
       [ 0.,  0.],
       [ 1.,  1.],
       [ 1., -1.],
       [ 1.,  0.]], dtype=float32)

#### Se cargan las salidas de la compuerta XOR

In [7]:
datos_salida = np.array([[1,0,0,1],[1,0,0,1],[1,0,0,1],[0,1,0,1],[1,0,1,0],[1,0,0,1],[0,1,1,0],[0,1,1,0],[0,1,1,0]], "float32")

#### Se programa la Red Neuronal

In [8]:
model = Sequential()
model.add(Dense(18, input_dim=2, activation='relu'))
model.add(Dense(4, activation='sigmoid'))

model.compile(loss='mean_squared_error', optimizer='adam', metrics=['binary_accuracy'])

model.fit(datos_entrenamiento, datos_salida, epochs=200)

Epoch 1/200
1/1 [==============================] - 1s 505ms/step - loss: 0.2820 - binary_accuracy: 0.4167
Epoch 2/200
1/1 [==============================] - 0s 8ms/step - loss: 0.2812 - binary_accuracy: 0.4167
Epoch 3/200
1/1 [==============================] - 0s 8ms/step - loss: 0.2804 - binary_accuracy: 0.4444
Epoch 4/200
1/1 [==============================] - 0s 8ms/step - loss: 0.2796 - binary_accuracy: 0.4722
Epoch 5/200
1/1 [==============================] - 0s 8ms/step - loss: 0.2788 - binary_accuracy: 0.4722
Epoch 6/200
1/1 [==============================] - 0s 8ms/step - loss: 0.2780 - binary_accuracy: 0.5000
Epoch 7/200
1/1 [==============================] - 0s 16ms/step - loss: 0.2772 - binary_accuracy: 0.5000
Epoch 8/200
1/1 [==============================] - 0s 8ms/step - loss: 0.2764 - binary_accuracy: 0.5000
Epoch 9/200
1/1 [==============================] - 0s 8ms/step - loss: 0.2757 - binary_accuracy: 0.5000
Epoch 10/200
1/1 [==============================] - 0s 8ms/st

#### Se evaluá el modelo

In [9]:
scores = model.evaluate(datos_entrenamiento, datos_salida)

print(model.metrics_names[1], scores[1]*100)
print(model.predict(datos_entrenamiento).round())

1/1 [==============================] - 0s 175ms/step - loss: 0.1504 - binary_accuracy: 0.9444
binary_accuracy 94.44444179534912
1/1 [==============================] - 0s 81ms/step
[[1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 1.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]]
